name: CoreKitpmap
author: Atom-Valres
api: [5.0.0]
version: 0.0.1
main: Valres\CoreKitmap\Core

permissions:
  #Grades    :
  addgrade.command:
    default: op
  gradelist.command:
    default: op
  #Sanctions :
  alias.command:
    default: op
  ban.command:
    default: op
  banlist.command:
    default: op
  blacklist.command:
    default: op
  casier.command:
    default: op
  ip-ban.command:
    default: op
  ip-unban.command:
    default: op
  mute.command:
    default: op
  mutelist.command:
    default: op
  unbanall.command:
    default: op
  unban.command:
    default: op
  unmute.command:
    default: op
  uuid-ban.command:
    default: op
  uuid-unban.command:
    default: op