name: CoreKitpmap
author: Atom-Valres
api: [5.0.0]
version: 1.0.0
main: Valres\CoreKitmap\Core

permissions:
  #Credit    :
  mycredit.command:
    default: true
  #Shop      :
  addcat-shop.command:
    default: op
  additem-shop.command:
    default: op
  editcat-shop.command:
    default: op
  edititem-shop.command:
    default: op
  #Box       :
  spawn-box.command:
    default: op
  add-box.command:
    default: op
  edit-box.command:
    default: op
  settings.command:
    default: true
  #Combat    :
  stats.command:
    default: op
  change-kb.command:
    default: op
  #Grades    :
  addgrade.command:
    default: op
  gradelist.command:
    default: op
  #Money     :
  mymoney.command:
    default: true
  pay.command:
    default: true
  seemoney.command:
    default: true
  topmoney.command:
    default: true
  add-money.command:
    default: op
  reduce-money.command:
    default: op
  set-money.command:
    default: op
  #Sanctions :
  alias.command:
    default: op
  ban.command:
    default: op
  banlist.command:
    default: op
  blacklist.command:
    default: op
  casier.command:
    default: op
  ip-ban.command:
    default: op
  ip-unban.command:
    default: op
  mute.command:
    default: op
  mutelist.command:
    default: op
  unbanall.command:
    default: op
  unban.command:
    default: op
  unmute.command:
    default: op
  uuid-ban.command:
    default: op
  uuid-unban.command:
    default: op
