#
# {bans}/{mutes} -> Nombres de bans/mutes du joueur.
#    {player}    -> Nom du joueur.
#     {date}     -> Date de la sanction.
#    {reason}    -> Raison de la sanction.
#    {author}    -> Auteur de la sanction.
#

webhook-url: ""

no-players: "§cCe joueur n'existe pas ou ne c'est jamais connecté."

casier-title: "Voiçi le casier de {player}:"
casier-ban-title: "Bans ({bans}):"
casier-ban-lines: "Ban le {date} pour {reason} par {author}"
casier-mute-title: "Mutes ({mutes}):"
casier-mute-lines: "Ban le {date} pour {reason} par {author}"

banlist-title: "Ban total ({bans}):"
banlist-lines: "{type} : {player} le {date} pour {reason} par {author}"
mutelist-title: "Mute total ({mutes}):"
mutelist-lines: "Mute : {player} le {date} pour {reason} par {author}"

alias-title: "Possible DC de {player}:"
alias-account-title: "Comptes liés aux IP:"
alias-account-lines: "- {pseudo}"
alias-ip-title: "IPs liées à ce pseudo:"
alias-ip-lines: "- {ip}"
alias-uuid-title: "Uuids liées à ce pseudo:"
alias-uuid-lines: "- {uuid}"

blacklist: "§cTout les comptes possible de {player} viennent d'être blacklist."
blacklist-login-message: "§cTout vos comptes/IPs ont été blacklist de ce serveur."

already-ban-message: "§cCe joueur est déja ban."
not-ban-message: "§cCe joueur n'est pas ban."
ban-login-message: "§cVous êtes banni de ce serveur.\nRaison: {reason}\nPendant: {time}\nPar: {author}"
ban-message: "§cLe joueur {player} vient d'être ban pour {reason}, pendant {time} par {author} !"
ip-ban-message: "§cToutes les IPs de {player} viennent d'être ban."
ip-unban-message: "§cToutes les IPs de {player} viennent d'être unban."
uuid-ban-message: "§cToutes les Uuids de {player} viennent d'être ban."
uuid-unban-message: "§cToutes les Uuids de {player} viennent d'être unban."
unban-message: "§cLe joueur {player} vient d'être unban par {author} !"
unban-all-message: "§cTout les joueurs, IPs et Uuid viennent d'être unban ! (pas les blacklist)"
ban-embed:
  title: "Ban system:"
  description: "Nouveau ban: {player}\nRaison: {reason}\nPendant: {time}"
  footer: "Ban par: {author}"

already-mute-message: "§cCe joueur est déja mute."
not-mute-message: "§cCe joueur n'est pas mute."
mute-player-message: "§cVous êtes encore mute pendant {time} pour {reason}."
mute-message: "§cLe joueur {player} vient d'être mute pour {reason}, pendant {time} par {author} !"
unmute-message: "§cLe joueur {player} vient d'être unmute par {author} !"
mute-embed:
  title: "Mute system:"
  description: "Nouveau mute: {player}\nRaison: {reason}\nPendant: {time}"
  footer: "Mute par: {author}"